### ISSUE TITLE
No wiring diagram? Could you please add it?

### ISSUE THREAD

**Issue by Anycubic** [alexmohr/open-heat#10]
Hello, I set up everything and all is working fine! Now I "only" need to add the valves in the loop, I have some Eqiva model without BT, could you please share a general connections/circuit diagram?
Thanks a lot for this project, it is looking very promising!

**Comment by alexmohr** [comment]
fyi @Anycubic the latest commit on the `deepSleep` branch adds two new mqtt topics to monitor the battery voltage and battery percentage

**Comment by Anycubic** [comment]
You did it! I'm going to test it asap, thank you!

**Comment by alexmohr** [comment]
It noticed that for my batteries the maximum voltage is rather 4.2 than 3.7V so I'll update that code soon, but the voltage itself is sent via mqtt as well

**Comment by Anycubic** [comment]
Regarding the diagram, is the LDO voltage regulator really necessary? Isn't the voltage divider with resistors only enough?

**Comment by alexmohr** [comment]
I've been using the voltage regulator for a while now to protect the esp from being fried on a accident. 
The voltage divider is enough to read the supply voltage
