### ISSUE TITLE
Implementing longest deep sleep during night time

### ISSUE THREAD

**Issue by Anycubic** [alexmohr/open-heat#11]
What about having longest deep sleep during night time (i.e. 2 hours) to increase batteries duration?

**Comment by Anycubic** [comment]
Not properly tied to this topic, could you please tell me which variable do I need to change to have a longest WIFI modem deepsleep? I'm doing tests with 2 18650 batteries in parallel, I guess waking up every 15 minutes or so instead of 5 will also make a difference

**Comment by alexmohr** [comment]
I'm using the same battery setup. To change the modem sleep time to 15 minutes change checkIntervalMillis_ in MQTT.hpp to 15*60*1000

**Comment by alexmohr** [comment]
Would it also be an option for you if you could send the device into modem sleep via mqtt instead of a time based approach?
You could send the command via home assitant automation https://www.home-assistant.io/docs/automation/trigger/#time-trigger

**Comment by Anycubic** [comment]
It could be interesting but and once it is sleeping how to wake it up again? How would like you to make it work?

**Comment by alexmohr** [comment]
You would send the sleep time in seconds.

**Comment by Anycubic** [comment]
Ok, so I could also write an automation script and let the valve sleep for long periods, i.e. during night hours. But what about if I should forget the valve switched on before running the script? No way to turning it off until the day after? Sounds risky

**Comment by alexmohr** [comment]
Correct and exactly the same would be true when you are doing this time based like you suggest in this issue. I suggest to close this.

**Comment by alexmohr** [comment]
I'll implement the sleep time configuration on the webinterface, but in way you can also set it via mqtt. 
This way you can use it to extend the sleep times at night to 15minutes or so while keeping it at 5-7 at day.

**Comment by Anycubic** [comment]
Ok, it does make sense. But during night time 15 minutes are way too much, I mean I would switch radiators on and set them at low temperature, i.e. 18 just in case it's too cold outside. So for me no need to interact with them during night time. Of course this is just one of the possible scenarios

**Comment by alexmohr** [comment]
You are free to set whatever value you want
