### ISSUE TITLE
Problems with last night deepSleep build, no logs in serial and no WIFI connection

### ISSUE THREAD

**Issue by Anycubic** [alexmohr/open-heat#13]
Good morning, I just compiled and flashed last night build but I can't see any log anymore coming from the serial interface and after the first configuration no connection to WIFI anymore.
Flashed 2 different Esps but at no avail. Is there something broken in the build? Or is there some leftover in the previous flash which is creating issues? I use ESP-Home flasher to actually flash the bin.
Thank you

**Comment by alexmohr** [comment]
In fact it should be working with the nodemcu again. Unfortunately supplying power to the valve seems broken. Maybe because I'm not using a voltage regulator for the nodemcu version

**Comment by Anycubic** [comment]
Well I'm not working with a nodemcu anymore, only ESP-12F, so at least we can both test with the same hardware configuration.

**Comment by alexmohr** [comment]
Closing this as nodemcu is working properly again

**Comment by Anycubic** [comment]
Hello Alexander, sorry but now WIFI config is broken with ESP-12F :-(
Reverted back with 27/10 + latest commits for better valve management to see if now closing is working well

**Comment by alexmohr** [comment]
You mean the wifi configuration portal? 
If yes: That's actually broken for a long time. Probably it's even broken in the library. Maybe I will replace this with my own implementation in the future. It sometimes works if you reload without browser cache. 
I don't care  too much about that at the moment to be honest because I have a workaround 
```
SSID=your_ssid
PW="your_pw"
HOST="your_hostname"
UPDATE_USER="admin"
UPDATE_PW="letmein"
curl http://192.168.4.1/wifisave?s=$SSID&p=$PW&s1=$SSID&p1=&Hostname=$HOST&UpdateUsername=UPDATE_USER&UpdatePassword=$UPDATE_PW&ip=%28IP+unset%29&gw=192.168.2.1&sn=255.255.255.0&dns1=192.168.2.1&dns2=8.8.8.8
```

**Comment by Anycubic** [comment]
Ok, I'll test it with latest commit to see if indeed that's was the cuplrit

**Comment by Anycubic** [comment]
I confirm there is no issue, just a wifi configuration portal problem
