### ISSUE TITLE
BME280 Vin Pin

### ISSUE THREAD

**Issue by Anycubic** [alexmohr/open-heat#14]
Good morning, I see in the diagram BME280 Vin pin is wired to GPIO13 (I guess in order not to always feed the sensor so to save the battery). BUT in the  readme also open window led is wired to GPIO13 by default.
I also tried to connect BME280 Vin to GPIO13 (I didn't configure it for window led) but it seems to me the BME is not working in this way.
Could you help me?
Thanks a lot
Giuseppe

**Comment by alexmohr** [comment]
The readme is outdated and in the deep sleep branch the window sensor is not functional anymore. 
I'm concentrating on core functionality before re-adding support for this

**Comment by Anycubic** [comment]
Ok thanks. But how do I enable GPIO13 for BME280? Is it implemented already or it's just in the diagram for the time being?

**Comment by alexmohr** [comment]
It is implemented and working for me. You have to configure the pin on the Webinterface as well.

**Comment by Anycubic** [comment]
Ok, now I understood why there was a new field in the configuration interface, I guess I was sleeping and didn't catch its purpose :-D
