### ISSUE TITLE
STL file disappeared

### ISSUE THREAD

**Issue by Anycubic** [alexmohr/open-heat#28]
Hi, I'm working on a custom case STL. Could you please publish again the STL file? There are just Freecad files in Schematics folder but unfortunately Freecad crashes on startup on my Mac.

**Comment by alexmohr** [comment]
I can't publish STL files anymore as they are over 200mb large since I've added threads for the screw holes. GitHub does not allow auch large files.

**Comment by Anycubic** [comment]
Could you please zip it and share it to me? I've lost all of the old builds file and it seems to me I can't download it anymore

**Comment by alexmohr** [comment]
Not for the moment. The case is not tested yet and therefore I have no intention whatsoever to support it in anyway before getting it printed and trying it out.

**Comment by Anycubic** [comment]
I'm not going to use it "as is", I just need to take the part where it holds the valve. Also the old STL version will do the job

**Comment by Anycubic** [comment]
Nevermind, I just found an old zip with old STLs

**Comment by alexmohr** [comment]
Alright but be warned, I'm not sure if this works at all. That's why I'm very hesitant to share these untested things. 
If you design a custom case and probably better case it would be great if you would share it.

**Comment by Anycubic** [comment]
> Alright but be warned, I'm not sure if this works at all. That's why I'm very hesitant to share these untested things. If you design a custom case and probably better case it would be great if you would share it.

Of course I will share my work!!!
